### ISSUE TITLE
Move main package

### ISSUE THREAD

**Issue by SuperQ** [mr-karan/doggo#1]
It would be useful to move the main package files from `cmd` to `cmd/doggo`.

This way the standard `go get github.com/mr-karan/doggo/cmd/doggo` would produce the correct binary name in `$GOPATH/bin`

**Comment by mr-karan** [comment]
@SuperQ Thanks for reporting this! 

Can you try this now? Sorry, the issue got auto-closed because of the PR Merge. Feel free to reopen in case of issues.

**Comment by SuperQ** [comment]
Works perfectly, thanks!
