### ISSUE TITLE
main branch is outdated

### ISSUE THREAD

**Issue by chenrui333** [mr-karan/doggo#119]
👋 looks like you did release from dev and the main branch is [quite behind](https://github.com/mr-karan/doggo/compare/main...v0.6.3), I think it is better to have main (or whatever default branch) has the latest commits to avoid confusion. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/176061

**Comment by mr-karan** [comment]
I am doing a major release in sometime, please ignore that tag. Sorry for any confusion caused. Will close this issue once I create the release.

**Comment by mr-karan** [comment]
It's done: https://github.com/mr-karan/doggo/releases/tag/v1.0.0
