### ISSUE TITLE
Help text alignment seems off

### ISSUE THREAD

**Issue by zx8** [mr-karan/doggo#123]
Saw this tool on HN today, so thought I'd install it and give it a try.

First thing I noticed is that the help text seems slightly misaligned:

![image](https://github.com/mr-karan/doggo/assets/8544900/49b1093f-f97e-4ee5-8a82-4d13fb287bad)

I know it's not a major bug report, but figured it was worth letting you know about! 🙂

**Comment by mr-karan** [comment]
Thanks for reporting. Fixed in v1.0.1

**Comment by mr-karan** [comment]
![image](https://github.com/mr-karan/doggo/assets/5689132/d6ac5bdc-04a0-4cb3-9a77-214b3c57eedc)
Should be fine in the next release
