### ISSUE TITLE
No completions directory in v1.0.2 sources

### ISSUE THREAD

**Issue by lcheylus** [mr-karan/doggo#126]
I would like to package doggo v1.0.2 for OpenBSD and add shell completions.

The `completions` directory with Bash/Fish/Zsh is not available in v1.0.2 sources => see commit 4821589

**Comment by mr-karan** [comment]
@lcheylus Hey. Yes, actually the reason is that I've removed them from the code as they are now available with `doggo completions` command.

Docs: https://doggo.mrkaran.dev/docs/features/shell/

**Comment by lcheylus** [comment]
OK, I'm now using `doggo completions bash|fish|zsh` to add shell completions in my OpenBSD `doggo` package.
