### ISSUE TITLE
Scoop install fails

### ISSUE THREAD

**Issue by ThaDaVos** [mr-karan/doggo#139]
Cannot install dogo using `scoop install doggo` as it fails with below error:

![afbeelding](https://github.com/mr-karan/doggo/assets/5251028/15b6dd5d-fbba-471e-b69c-1e97cb4734f8)

**Comment by mr-karan** [comment]
Hey. Sorry, I don't maintain this. It's contributed externally by the community. https://github.com/mr-karan/doggo/pull/57

Probably the right place to open this issue would be https://github.com/ScoopInstaller/Main/

**Comment by thomasbilk** [comment]
I updated the JSON file and introduced the error. But it should be fixed now, the Pull Request is waiting to be merged.

**Comment by thomasbilk** [comment]
This should be fixed now.

**Comment by mr-karan** [comment]
Thanks! Marking it closed.
