### ISSUE TITLE
Incorrect handling of search list

### ISSUE THREAD

**Issue by sanxiyn** [mr-karan/doggo#3]
According to `resolv.conf(5)`, "Resolver queries having fewer than ndots dots (default is 1) in them will be attempted using each component of the search path in turn until a match is found". That is, search stops at the first match.

Given:

```
one.a.sanxiyn.name A 1.1.1.1
one.b.sanxiyn.name A 1.1.1.1
```

and

```
search a.sanxiyn.name b.sanxiyn.name
```

Querying `one` should return `one.a.sanxiyn.name`. doggo returns both.

**Comment by mr-karan** [comment]
@sanxiyn Understood the issue. I am fetching all the possible domains before hitting the DNS server [here](https://github.com/mr-karan/doggo/blob/main/cmd/doggo/lookup.go#L84). I'll have to change the `Lookup` method to incorporate this change. Needs some restructuring of the code, so putting on my TODO for the next version.

**Comment by mr-karan** [comment]
@sanxiyn  The fix is available in https://github.com/mr-karan/doggo/releases/tag/v0.2.0
