### ISSUE TITLE
Installation via scoop

### ISSUE THREAD

**Issue by wsw70** [mr-karan/doggo#36]
It would be awesome if `doggo` was added to [`scoop` ](https://scoop.sh/). It would probably help the expansion and plan to take over `nslookup`and `dig`.

https://ibigbug.online/how-to-publish-a-scoop-package published some information about how to do it in practical terms, and detailed information is at https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests

**Comment by mr-karan** [comment]
PR is appreciated.
