### ISSUE TITLE
rtt measurement is unfair

### ISSUE THREAD

**Issue by wen-long** [mr-karan/doggo#39]
* rtt in Classic mode, is not including transport layer Dial time 

       >  Dial before rtt timer start  
      https://github.com/miekg/dns/blob/55216486109ae476af60b09a456281903fa2888e/client.go#L164

  https://github.com/mr-karan/doggo/blob/79c5fc72837404cfef96ce9dcd5cae3343931655/pkg/resolvers/classic.go#L68

* rtt in doh, including transport layer Dial time

  https://github.com/mr-karan/doggo/blob/79c5fc72837404cfef96ce9dcd5cae3343931655/pkg/resolvers/doh.go#L62

you can test with a large latency doh server, and will find that tcp dial time can not be ignored
there is a server list https://kb.adguard.com/en/general/dns-providers

**Comment by mr-karan** [comment]
This is how the upstream library records RTT. For `doggo` to have a fair time report, I think we should declare our own `time.Now()` even for Classic resolver and not depend on `rtt` provided by the library.

Would that solve this issue? @wen-long

**Comment by wen-long** [comment]
> 

Yes, I aggre
