### ISSUE TITLE
win10 x64 system displays garbled characters

### ISSUE THREAD

**Issue by thb007** [mr-karan/doggo#40]
![ZJWHWPDUCDNNFQ{0MAIJ4{G](https://user-images.githubusercontent.com/17548936/173048188-d5e8a514-76d3-476d-8526-d2086acc61d3.png)
![}83~)WNKTTKP%E$77NC09NE](https://user-images.githubusercontent.com/17548936/173048204-0e103641-8b36-4aac-b971-7e3fa1f6f4ea.png)

**Comment by mr-karan** [comment]
Unsure about Windows as I don't have access to a test machine. Maybe you can use `--color=false`, like `doggo mrkaran.dev --color=false`. 

PR is appreciated for it.

**Comment by thb007** [comment]
> Unsure about Windows as I don't have access to a test machine. Maybe you can use `--color=false`, like `doggo mrkaran.dev --color=false`.
> 
> PR is appreciated for it.

doggo mrkaran.dev --color=false is displayed normally, but more commands need to be written

**Comment by mapl** [comment]
Try Windows Terminal https://github.com/microsoft/terminal

![image](https://user-images.githubusercontent.com/9784732/175132350-8b732ef5-2f62-4300-9d0e-95a34ece39e5.png)

**Comment by thb007** [comment]
> Try Windows Terminal https://github.com/microsoft/terminal
> 
> ![image](https://user-images.githubusercontent.com/9784732/175132350-8b732ef5-2f62-4300-9d0e-95a34ece39e5.png)

thanks
