### ISSUE TITLE
GPL-3.0 is a deprecated SPDX license

### ISSUE THREAD

**Issue by chenrui333** [mr-karan/doggo#43]
[GPL-3.0](https://spdx.org/licenses/GPL-3.0.html) is deprecated by SPDX, please consider using [GPL-3.0-only ](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html). Thanks!

relates to Homebrew/homebrew-core#104286

**Comment by mr-karan** [comment]
@chenrui333 Hi. I've used the LICENSE text from https://choosealicense.com/licenses/gpl-3.0/#. If you click on the `Source` in the text page, it redirects to https://spdx.org/licenses/GPL-3.0-or-later.html which is the one you suggested. 

Sorry if I'm missing something here, the LICENSE looks alright according to the above information?

**Comment by chenrui333** [comment]
Yeah, you missed the license header info (the only difference between -only and -or-later). But thanks for clarifying it though!

**Comment by chenrui333** [comment]
@mr-karan I filed a PR to include the license header into the README, let me know if that works for you. Thanks!

**Comment by mr-karan** [comment]
Sure, thanks a lot!
