### ISSUE TITLE
Packing doggo for Nix 

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [mr-karan/doggo#51]
Hi,

I recently needed to use `doggo` but could not find it for Nix(OS). I therefore created a Nix package and opened a [pull request](https://github.com/NixOS/nixpkgs/pull/186894) for it on [Nixpkgs](https://github.com/nixos/nixpkgs).
I just wanted to share this here in case someone will participate in it.

**Comment by mr-karan** [comment]
@GeorgesAlkhouri Thanks a lot for this. I'll definitely add this in the README once it's merged!

**Comment by GeorgesAlkhouri** [comment]
Cool. Let's hope it doesn't take too long 😄 So far, the PR was sucessfully reviewed and is waiting to be merged.

**Comment by GeorgesAlkhouri** [comment]
@mr-karan what do you think about the [License discussion ](https://github.com/NixOS/nixpkgs/pull/186894#discussion_r953200346)?

**Comment by mr-karan** [comment]
@GeorgesAlkhouri That was indeed something that I missed. Have fixed https://github.com/mr-karan/doggo/commit/0da9178683b435abf80d5e2a229cd8d30a0f64fc

**Comment by iAmMrinal0** [comment]
Came here to package this for Nix. thanks for the PR @GeorgesAlkhouri!
