### ISSUE TITLE
Exit codes on resolve errors

### ISSUE THREAD

**Issue by SISheogorath** [mr-karan/doggo#53]
Currently doggo doesn't provide any error exit code when it can't reach any resolver:

https://github.com/mr-karan/doggo/blob/0da9178683b435abf80d5e2a229cd8d30a0f64fc/cmd/doggo/cli.go#L150-L164

This would be really useful not only to indicate to shell integrations, that the command failed, but also when using doggo in any kind of script, to allow error handling.

`dig` for example returns an exit code 9, when trying to query 127.0.0.1 and no DNS server is available. doggo returns 0 when running: `podman run --rm -it ghcr.io/mr-karan/doggo:latest mrkaran.dev @127.0.0.1` same as `run ghcr.io/mr-karan/doggo:latest mrkaran.dev @9.9.9.9`, while the former fails, the latter is successful.

So I wonder what would be the expectation for this feature? Should it mimic dig exit codes? Should it just be 2 like many other errors? Should it stay as it is?

**Comment by mr-karan** [comment]
Proper exit codes definitely make sense. I'll investigate this. It's fine to mimic `dig` so people using an alternative in CI pipelines/bash scripts don't have to change much.

**Comment by SISheogorath** [comment]
My 5 minutes of fiddling solution looks like this:

```patch
diff --git a/cmd/doggo/cli.go b/cmd/doggo/cli.go
index fe5d550..8c213e5 100644
--- a/cmd/doggo/cli.go
+++ b/cmd/doggo/cli.go
@@ -149,16 +149,21 @@ func main() {
 
        // Resolve Queries.
        var responses []resolvers.Response
+       var responseErrors []error
        for _, q := range app.Questions {
                for _, rslv := range app.Resolvers {
                        resp, err := rslv.Lookup(q)
                        if err != nil {
                                app.Logger.WithError(err).Error("error looking up DNS records")
+                               responseErrors = append(responseErrors, err)
                        }
                        responses = append(responses, resp)
                }
        }
        app.Output(responses)
+       if len(responseErrors) > 0 {
+               app.Logger.Exit(9)
+       }
 
        // Quitting.
        app.Logger.Exit(0)
```

I have to say, I'm not the greatest go coder, so if there is any suggestion how to do this nicer, it's more than welcome, otherwise I'll open a PR.

**Comment by mr-karan** [comment]
The thing is, that the current behaviour only outputs the error. So, if there's an error with one resolver, but the other one works fine, then even `dig` outputs exit code of 0 and not 9:

```
dig mrkaran.dev @1.1.1.1 @2.2.2.2 +short
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

```
echo $?
0
```

So, maybe we can do exit only when this condition is true:`if len(responses)==0 && len(responseErrors)>0`. And it has to come before we call `app.Output`.
