### ISSUE TITLE
doggo issues on Windows

### ISSUE THREAD

**Issue by jungle-boogie** [mr-karan/doggo#6]
Hi,

Thanks for your project. I'm using Windows 10 19041.685 and this is the output when using doggo:

```
> doggo.exe github.com
time="2020-12-18T21:52:35-08:00" level=error msg="error loading nameservers" error="error fetching system default nameserver"
```

I think I need to put @9.9.9.9 in quotes but doing so, generates this:

```
> doggo mrkaran.dev MX "@9.9.9.9"
time="2020-12-18T21:56:03-08:00" level=error msg="error looking up DNS records" error="dns: domain must be fully qualified"
```

Ah, I think this explains it:
https://github.com/mr-karan/doggo/blob/main/cmd/doggo/nameservers.go#L61

**Comment by mr-karan** [comment]
Hey. I happened to fix this just now, please try [v0.1.1](https://github.com/mr-karan/doggo/releases/tag/v0.1.1) :) and let me know if the issue persists.

**Comment by jungle-boogie** [comment]
> but the second error you were seeing should be gone now.

Looks good!

> doggo archive.org "@https://cloudflare-dns.com/dns-query"
NAME            TYPE    CLASS   TTL     ADDRESS         NAMESERVER
archive.org.    A       IN      17s     207.241.224.2   https://cloudflare-dns.com/dns-query

> doggo duckduckgo.com --time "@https://cloudflare-dns.com/dns-query"
NAME            TYPE    CLASS   TTL     ADDRESS         NAMESERVER                              TIME TAKEN
duckduckgo.com. A       IN      12s     52.250.42.157   https://cloudflare-dns.com/dns-query    134ms

> doggo github.com "@9.9.9.9"
NAME            TYPE    CLASS   TTL     ADDRESS         NAMESERVER
github.com.     A       IN      15s     192.30.255.112  9.9.9.9:53

> doggo mrkaran.dev MX "@9.9.9.9"
NAME            TYPE    CLASS   TTL     ADDRESS                         NAMESERVER
mrkaran.dev.    MX      IN      300s    10                              9.9.9.9:53
                                        in1-smtp.messagingengine.com.
mrkaran.dev.    MX      IN      300s    20                              9.9.9.9:53
                                        in2-smtp.messagingengine.com.
```

**Comment by mr-karan** [comment]
Cool. Closing this, as I am tracking the progress for first error separately and would try to push for the next release.
