### ISSUE TITLE
Feature Suggestion: Http3 Support

### ISSUE THREAD

**Issue by Sunsetra** [mr-karan/doggo#61]
Some of the dns server have supported http3 connection (e.g. Google and Cloudflare). Maybe doggo can also add http3 support in the future, or the http3 support has been in progress?

**Comment by mr-karan** [comment]
Do you mean `quic` support? Then doggo already supports it.

```
doggo github.com @quic://dns.adguard.com 

NAME       	TYPE	CLASS	TTL	ADDRESS     	NAMESERVER          
github.com.	A   	IN   	46s	20.207.73.82	dns.adguard.com:784
```

**Comment by Sunsetra** [comment]
Yes you are right, how can I ignore quic support😤
Thanks, I will close this.

**Comment by wen-long** [comment]
Wait, That's not right

https://community.cloudflare.com/t/dns-settings-for-dns-over-http-3-dns-over-quic-on-android/400931/9

> DNS over HTTP/3 is not DNS over QUIC.
> DNS over HTTP/3 is based on DNS over HTTPS (DoH), but supports the HTTP/3 protocol (I’m actually curious if common DNS resolvers can recognise and use HTTP/3 properly).
> DNS over QUIC (DoQ) is based directly on the QUIC protocol and uses the same port 853 as DNS over TLS (DoT) by default, but with UDP.

**Comment by wen-long** [comment]
any comment on this?
@mr-karan

**Comment by kmahyyg** [comment]
Any update?

**Comment by ColinZeb** [comment]
Request to reopen the issue.
