### ISSUE TITLE
Is it possible to test localhost DoH server ?

### ISSUE THREAD

**Issue by issuex** [mr-karan/doggo#65]
I have try to test my DoH server (self-sign) at localhost by run 
`doggo -q www.google.com -t A @https://127.0.0.1:8353/dns-query`
it said
`certificate signed by unknown authority`
Do you have any argument to bypass it ?

**Comment by mr-karan** [comment]
@issuex Hi. Sorry for the late response. Can you let me know how does `dig` handle this currently?
