### ISSUE TITLE
doq request don't work

### ISSUE THREAD

**Issue by Temciuc** [mr-karan/doggo#69]
$ doggo archive.org @quic://dns.adguard.com
ERROR[2023-04-12T15:19:24+03:00] error looking up DNS records                  error="dial udp: lookup quic://dns.adguard.com: no such host"

**Comment by tinyboxvk** [comment]
```
> doggo archive.org @quic://dns.adguard.com
NAME            TYPE    CLASS   TTL     ADDRESS         NAMESERVER
archive.org.    A       IN      296s    207.241.224.2   dns.adguard.com:853
```

Is your current DNS server able to resolve dns.adguard.com?

**Comment by mr-karan** [comment]
Works fine. Maybe your local network isn't able to resolve `dns.adguard.com` as @tinyboxvk suggested.
