### ISSUE TITLE
doggo cannt work well on wsl1

### ISSUE THREAD

**Issue by honulu** [mr-karan/doggo#9]
I installed `doggo` on wsl1, and this is the output when using `doggo`.
```bash
> doggo baidu.com
ERROR[2020-12-22T17:22:44+08:00] error looking up DNS records                  error="read udp [2001:0:2851:b9f0:2444:b43f:496b:c4f4]:54677->[fec0:0:0:ffff::1]:53: i/o timeout"
```

**Comment by mr-karan** [comment]
Can you show the contents of `/etc/resolv.conf` please? I'll try reproducing with that.

**Comment by honulu** [comment]
The contents of `reslolv.conf` are as follows
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 192.168.0.1
nameserver fec0:0:0:ffff::1
nameserver fec0:0:0:ffff::2
```
I found when i stop automatic generation `reslov.conf`, and only add  ipv4 nameserver `192.168.0.1` to `reslov.conf`, doggo will work well.

**Comment by mr-karan** [comment]
@honulu Can you try v0.2.2 ? :) 

https://github.com/mr-karan/doggo/releases/tag/v0.2.2
