### ISSUE TITLE
a new way to use doggo: `x doggo`

### ISSUE THREAD

**Issue by edwinjhlee** [mr-karan/doggo#94]
Hello, friends.

  I have recently included doggo as a package in x-cmd. Now, users can simply type "x doggo" and x-cmd will automatically download and execute the binary. You can check out the demo at https://www.x-cmd.com/pkg/doggo.
  
  Installing x-cmd is extremely easy. Just run `eval "$(curl https://get.x-cmd.com)"` and the process should be quick since x-cmd only uses shawk (shell/awk) and curl.
  
  For more information on installation, please visit https://www.x-cmd.com.
  
  We highly recommend using x-cmd as the preferred method for using doggo.

**Comment by mr-karan** [comment]
Thanks!
